import './globals.css'
import type { Metadata } from 'next'
import { Lekton, Roboto } from 'next/font/google'

const lekton = Lekton({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: "--font-lekton",
})

const roboto = Roboto({
  weight: ['500', '700'],
  subsets: ['latin'],
  variable: "--font-roboto",
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${lekton.variable} ${roboto.variable}`}>
      <body>{children}</body>
    </html>
  )
}
