"use client"
import { v4 as uuidv4 } from 'uuid';
import { createContext } from "react";

const data = {
  title: "Create Next App",
  description: "Generated by create next app",
  about: {
    title: "About Me",
    subtitle: "Is there anything I can do for you?",
    gretting: "Hello! I’m Donald Wellborn.",
    desc: "Back-end Frond-end developer from UK, London. I have rich experience in wordpress, also I am good at Magento. I love to talk width you about our unique.",
    list: [
      { id: uuidv4(), data: "Age", value: "36" },
      { id: uuidv4(), data: "Residence", value: "CO" },
      { id: uuidv4(), data: "Freelance", value: "Available" },
      { id: uuidv4(), data: "Address", value: "Bogota, Colombia" },
    ],
    block: [
      {
        id:   uuidv4(),
        icon: "code",
        name: "Front-end", 
        desc: "Modern and mobile-ready website that will help you reach all of your marketing.",
      },
      {
        id:   uuidv4(),
        icon: "ui",
        name: "UX / UI",
        desc: "UI/UX focus on the user, frontend focus on the settings of the user.",
      },
      {
        id:   uuidv4(),
        icon: "wordpress",
        name: "WordPress Development",
        desc: "WordPress development services improve business websites.",
      },
      {
        id:   uuidv4(),
        icon: "shield",
        name: "WordPress Security",
        desc: "Security consultants can check the code and scan for vulnerabilities.",
      }
    ]
  },
  resume: {
    title: "Experience",
    subtitle: "What I've done",
    blockExperience: [
      {
        title: "Experience",
        desc: "--",
        experiences: [
          {
            id:   uuidv4(),
            actual: true,
            date: "2018 - Present",
            name: "Team Leader", 
            company: "Facebook Inc.",
            desc: "Collaborate width creative and development teams."
          },
          {
            id:   uuidv4(),
            actual: false,
            date: "2018 - Present",
            name: "Team Leader", 
            company: "Facebook Inc.",
            desc: "Collaborate width creative and development teams."
          },
          {
            id:   uuidv4(),
            actual: false,
            date: "2018 - Present",
            name: "Team Leader",
            company: "Facebook Inc.",
            desc: "Collaborate width creative and development teams."
          },
          {
            id:   uuidv4(),
            actual: false,
            date: "2018 - Present",
            name: "Team Leader",
            company: "Facebook Inc.",
            desc: "Collaborate width creative and development teams."
          }
        ]
      }
    ],
    blockEducation: [
      {
        title: "Education",
        desc: "--",
        educations: [
          {
            id:   uuidv4(),
            date: "2018 - Present",
            name: "Team Leader",
            company: "Facebook Inc.",
            desc: "Collaborate width creative and development teams."
          },
          {
            id:   uuidv4(),
            date: "2018 - Present",
            name: "Team Leader",
            company: "Facebook Inc.",
            desc: "Collaborate width creative and development teams."
          }
        ]
      }
    ],
    blockCertificate: [
      {
        title: "Certificate",
        desc: "--",
        certificates: [
          {
            id:   uuidv4(),
            date: "2018 - Present",
            name: "Team Leader",
            company: "Facebook Inc.",
            desc: "Collaborate width creative and development teams."
          },
          {
            id:   uuidv4(),
            date: "2018 - Present",
            name: "Team Leader",
            company: "Facebook Inc.",
            desc: "Collaborate width creative and development teams."
          },
          {
            id:   uuidv4(),
            date: "2018 - Present",
            name: "Team Leader",
            company: "Facebook Inc.",
            desc: "Collaborate width creative and development teams."
          }
        ]
      }
    ],
    blockSkills: [
      {
        title: "Skills",
        desc: "--",
        skills: [
          {
            id:   uuidv4(),
            name: "html",
            image: "logo-html.png",
            width: 72,
            height: 72,
          },
          {
            id:   uuidv4(),
            name: "css",
            image: "logo-css.png",
            width: 72,
            height: 72,
          },
          {
            id:   uuidv4(),
            name: "javascript",
            image: "logo-javascript.png",
            width: 72,
            height: 72,
          },
          {
            id:   uuidv4(),
            name: "react",
            image: "logo-react.png",
            width: 72,
            height: 72,
          },
          {
            id:   uuidv4(),
            name: "next",
            image: "logo-next.png",
            width: 72,
            height: 72,
          },
          {
            id:   uuidv4(),
            name: "typescript",
            image: "logo-typescript.png",
            width: 72,
            height: 72,
          },
          {
            id:   uuidv4(),
            name: "sass",
            image: "logo-sass.png",
            width: 72,
            height: 72,
          },
          {
            id:   uuidv4(),
            name: "tailwind",
            image: "logo-tailwind.png",
            width: 72,
            height: 72,
          },
          {
            id:   uuidv4(),
            name: "sql",
            image: "logo-sql.png",
            width: 72,
            height: 72,
          },
          {
            id:   uuidv4(),
            name: "figma",
            image: "logo-figma.png",
            width: 72,
            height: 72,
          },
          {
            id:   uuidv4(),
            name: "xd",
            image: "logo-xd.png",
            width: 72,
            height: 72,
          },
          {
            id:   uuidv4(),
            name: "wordpress",
            image: "logo-wordpress.png",
            width: 72,
            height: 72,
          }
        ]
      }
    ]
  }
}

export const DataContext = createContext(data)

export const DataContextProvider = ({ children }: any) => {
  return (
    <DataContext.Provider value={data}>
      {children}
    </DataContext.Provider>
  )
}